### ISSUE TITLE
Live demo not working

### ISSUE THREAD

**Issue by rohanrehman** [brakmic/Angular2_VR_Starter#1]
iPhone 6 not working in safari not chrome. Seems like a layout issue.

**Comment by brakmic** [comment]
On iPhone all browsers run the same rendering engine (Webkit). Therefore it's irrelevant if your browser is called "chrome" or "safari", it's the same engine. That's because Apple forbids usage of non-Apple rendering engines on Apple hardware. As I have no apple device here I can't test it thoroughly. "layout issue" alone is not enough information to improve the demo. Maybe you can checkout the sources from this repo and try to run the demos "locally"?

Kind regards,

**Comment by amity203** [comment]
live demo not working on chrome on my macbook

**Comment by brakmic** [comment]
There could be many different reasons but because this code was "just a demo" I'll leave it as it is. Meanwhile I'm working on other projects so I don't have time to debug MacOS stuff. I don't even own a Mac 😅

**Comment by amity203** [comment]
Cool, no issues, as aframe itself has any demo, but i am looking from angular prospective as i am trying to do it in ionic 2 framework
